- name: Run common tasks to all hosts
  hosts: all
  remote_user: "{{ user }}"
  gather_facts: false

  tasks:
    - name: Fix the dns issues
      ansible.builtin.shell: |
        unlink /etc/resolv.conf && echo 'nameserver 1.1.1.1' > /etc/resolv.conf
      changed_when: false
