---
# Master playbook to run once the whole configuration.
# Check the specific playbooks and roles to have more information.
- import_playbook: bootstrap.yml
#- import_playbook: modern-bpf-test.yml
- import_playbook: git-repos.yml
- import_playbook: scap-open-test.yml
