# Playbook used to run scap-open-test role.
# Check the role for more information
- name: Play that runs probes tests using scap-open binary
  hosts: all
  gather_facts: false
  remote_user: "{{ user }}"
  become: true
  serial: 30
  roles:
    - scap_open
