ARG VERSION=6.19.7-300
ARG HVERSION=6.19.6-300
ARG ARCHITECTURE=x86_64
ARG URL='https://archives.fedoraproject.org/pub/fedora/linux/development/44/Everything/aarch64/os/Packages/k/'

FROM initrd-builder:0.0.1 AS stage1

ARG VERSION
ARG HVERSION
ARG ARCHITECTURE
ARG URL

WORKDIR /home/ubuntu

RUN touch .placeholder && \
	curl -Lo kernel.rpm  ${URL}kernel-core-${VERSION}.fc44.${ARCHITECTURE}.rpm     && \
	curl -Lo headers.rpm ${URL}kernel-headers-${HVERSION}.fc44.${ARCHITECTURE}.rpm && \
	curl -Lo modules.rpm ${URL}kernel-modules-${VERSION}.fc44.${ARCHITECTURE}.rpm  && \
	curl -Lo sources.rpm ${URL}kernel-devel-${VERSION}.fc44.${ARCHITECTURE}.rpm    && \
	curl -Lo modules-core.rpm ${URL}kernel-modules-core-${VERSION}.fc44.${ARCHITECTURE}.rpm  && \
	rpm2cpio kernel.rpm  > kernel.cpio  && \
	rpm2cpio headers.rpm > headers.cpio && \
	rpm2cpio modules.rpm > modules.cpio && \
	rpm2cpio sources.rpm > sources.cpio && \
	rpm2cpio modules-core.rpm > modules-core.cpio && \
	mkdir extracted && \
	cd extracted && \
	cpio -idmv < ../kernel.cpio  && \
	cpio -idmv < ../headers.cpio && \
	cpio -idmv < ../modules.cpio && \
	cpio -idmv < ../sources.cpio && \
	cpio -idmv < ../modules-core.cpio
RUN cd /home/ubuntu/extracted && \
    find . -name '*.xz' -exec xz -d {} \; && \
	extract-vmlinux $(find lib/modules -name vmlinuz) > /home/ubuntu/extracted/vmlinux

FROM fedora:44 AS kmod-builder

ARG VERSION
ARG HVERSION
ARG URL
ARG ARCHITECTURE

WORKDIR /home/ubuntu
COPY --from=stage1 /home/ubuntu/extracted /home/ubuntu/extracted/
COPY --from=stage1 /opt/initrd-builder/*    /opt/initrd-builder/


RUN dnf install --disablerepo=updates-testing -y @development-tools && \
	cp -v /opt/initrd-builder/Makefile.virtio_mmio Makefile && \
	curl -LO 'https://gitlab.com/cki-project/kernel-ark/-/raw/fedora-6.19/drivers/virtio/virtio_mmio.c' && \
	KERNEL_DIR="/home/ubuntu/extracted/usr/src/kernels/${VERSION}.fc44.${ARCHITECTURE}/" make


FROM initrd-builder:0.0.1 AS stage2
COPY --from=stage1       /home/ubuntu/extracted      /home/ubuntu/extracted/
COPY --from=kmod-builder /home/ubuntu/virtio_mmio.ko /home/ubuntu/
RUN cd /home/ubuntu/extracted && \
	/opt/initrd-builder/create.sh

FROM scratch

COPY --from=stage1 /home/ubuntu/.placeholder /lib/modules/
COPY --from=stage1 /home/ubuntu/extracted/vmlinux /boot/
COPY --from=stage2 /home/ubuntu/out/initrd /boot/
