---
# tasks file for scap_open
- name: Setting output directory for results
  ansible.builtin.set_fact:
    output_dest_dir: "{{ output_dir }}/scap-open-test/{{ inventory_hostname }}"

- name: Create output directory on localhost
  become: false
  delegate_to: localhost
  block:
    - name: Create output directory if it does not exist ({{ output_dir }})
      ansible.builtin.file:
        path: "{{ output_dest_dir }}"
        state: directory
        mode: '0755'


- name: Prepare the build directory
  block:
    # TODO: move this elsewhere.
    - name: Fix the dns issues
      ansible.builtin.shell: |
        unlink /etc/resolv.conf && echo 'nameserver 1.1.1.1' > /etc/resolv.conf
      changed_when: false

    - name: Create cmake output dir
      ansible.builtin.file:
        path: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
        state: directory
        mode: "0755"
      register: cmake_result

    - name: Check btf support
      ansible.builtin.stat:
        path: /sys/kernel/btf/vmlinux
      register: btf_support

    - name: Prepare cmake for repository
      ansible.builtin.command:
        cmd: >
             cmake
             -DUSE_BUNDLED_DEPS=ON
             -DBUILD_LIBSCAP_MODERN_BPF={{ btf_support.stat.exists }}
             -DBUILD_LIBSCAP_GVISOR=OFF
             -DBUILD_BPF=true
             -DCREATE_TEST_TARGETS=OFF
             ..
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      changed_when: false
      register: cmake_result
  rescue:
    - name: Print error message to stdout --- build directory
      ansible.builtin.debug:
        var: cmake_result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ cmake_result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/cmake-build-directory.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Build scap-open binary
  block:
    - name: Build scap-open
      ansible.builtin.command:
        cmd: make scap-open -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: scap_open_result
      changed_when: false
  rescue:
    - name: Print error message to stdout --- build scap-open binary
      ansible.builtin.debug:
        var: scap_open_result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ scap_open_result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/build-scap-open-binary.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Build and load the kernel module
  block:
    - name: Unload the kernel module
      ansible.builtin.command:
        cmd: rmmod driver/scap.ko
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      failed_when: false
      changed_when: false

    - name: Build kmod
      ansible.builtin.command:
        cmd: make driver -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: km_result
      changed_when: false

    - name: Load the kernel module
      ansible.builtin.command:
        cmd: insmod driver/scap.ko
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: km_result
      changed_when: false
  rescue:
    - name: Print error message to stdout --- kernel module
      ansible.builtin.debug:
        var: km_result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ km_result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/build-kernel-module.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Scap-open + kernel module
  block:
    - name: Run scap-open with kernel module
      ansible.builtin.command:
        cmd: ./libscap/examples/01-open/scap-open --num_events 50 --kmod
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: result
      changed_when: false

    - name: Unload the kernel module
      ansible.builtin.command:
        cmd: rmmod driver/scap.ko
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: result
      changed_when: false
  rescue:
    - name: Print error message to stdout -- scap-open + kernel module
      ansible.builtin.debug:
        var: result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/scap-open-and-kernel-module.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Build bpf probe
  block:
    - name: Build bpf probe
      ansible.builtin.command:
        cmd: make bpf -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: bpf_probe_result
      changed_when: false
  rescue:
    - name: Print error message to stdout --- build bpf probe
      ansible.builtin.debug:
        var: result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ bpf_probe_result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/build-bpf-probe.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Scap-open + bpf probe
  block:
    - name: Run scap-open with bpf probe
      ansible.builtin.command:
        cmd: ./libscap/examples/01-open/scap-open --num_events 50 --bpf driver/bpf/probe.o
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: result
      changed_when: false
  rescue:
    - name: Print error message to stdout --- scap-open + bpf probe
      ansible.builtin.debug:
        var: result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/scap-open-and-bpf-probe.json"
        mode: '0755'
      delegate_to: localhost
      become: false

- name: Scap-open + modern probe
  block:
    - name: Run scap-open with modern-probe
      ansible.builtin.command:
        cmd: ./libscap/examples/01-open/scap-open --num_events 50 --modern_bpf
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      register: result
      when: btf_support.stat.exists
      changed_when: false
  rescue:
    - name: Print error message to stdout --- scap-open + modern probe
      ansible.builtin.debug:
        var: result
  always:
    - name: Dump error message to file
      ansible.builtin.copy:
        content: "{{ result | to_nice_json }}"
        dest: "{{ output_dest_dir }}/scap-open-and-modern-probe.json"
        mode: '0755'
      delegate_to: localhost
      become: false
