---
# tasks file for clean-up
# this role removes the cluster and the files created by the bootstrap role

- name: Find and save in a local variable all machines config files
  find:
    paths: ./roles/bootstrap/files
    patterns: "*.yaml"
  register: files_to_delete

- name: Delete all the machine config files files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"


# We search all the machines created for this run_id.
# We make sure that all machines are stopped and then delete them.
- name: Stop running machines and delete them
  block:
    - name: Get name of running machines run_id={{ run_id }}
      shell:
        cmd: ignite ps --all -f \{\{.Labels.run\}\}={{ run_id }},\{\{.Status.Running\}\}=true -t \{\{.Name\}\}
      register: vms

    - name: Stop running machines run_id={{ run_id }}
      shell:
       cmd: ignite kill {{item}}
      loop: "{{ vms.stdout_lines }}"

    - name: Get name of stopped machines run_id={{ run_id }}
      shell:
        cmd: ignite ps --all -f \{\{.Labels.run\}\}={{ run_id }} -t \{\{.Name\}\}
      register: vms

    - name: Delete machines run_id={{ run_id }}
      shell:
       cmd: ignite rm {{ item }}
      loop: "{{ vms.stdout_lines }}"
  become: true

# Ignite imports the images from the OCI ones and caches them.
# If the images change in the remote repository, ignite continues to use
# the cached ones. During the clean phase, we make sure to remove them from
# the cache.
- name: Remove rootfs and kernel images from ignite cache
  block:
    - name: List cached images
      shell:
       cmd: ignite images ls -q
      register: images
    
    - name: Remove cached images from ignite
      shell:
       cmd: ignite image rm {{ item }}
      loop: "{{ images.stdout_lines }}"
      
    - name: List cached kernels
      shell:
       cmd: ignite kernel ls -q
      register: kernels
    
    - name: Remove cached kernels from ignite
      shell:
       cmd: ignite kernel rm {{ item }}
      loop: "{{ kernels.stdout_lines }}"
  become: true
  ignore_errors: true

- name: Remove the files directory in the bootstrap role
  file:
    path: "./roles/bootstrap/files"
    state: absent

- name: Remove the inventory.ini file
  file:
    path: "./inventory.ini"
    state: absent