---
# tasks file for clean-up
# this role removes the cluster and the files created by the bootstrap role

- name: Find and save in a local variable all machines config files
  find:
    paths: ./roles/bootstrap/files
    patterns: "*.yaml"
  register: files_to_delete

- name: Delete all the machine config files files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Get name of vms and register them in variables
  shell:
    cmd: ignite ps --all -f \{\{.ObjectMeta.Name\}\}={{item.name}} -t \{\{.Name\}\} 
  register: vms
  become: yes
  loop: "{{ machines }}"

- name: Stop machines
  shell:
   cmd: ignite kill {{item.1}}
  become: yes
  loop: "{{ vms.results|subelements('stdout_lines') }}"

- name: Delete machines
  shell:
   cmd: ignite rm {{item.1}}
  become: yes
  loop: "{{ vms.results|subelements('stdout_lines') }}"

# Ignite imports the images from the OCI ones and caches them.
# If the images change in the remote repository, ignite continues to use
# the cached ones. During the clean phase, we make sure to remove them from
# the cache.
- name: Remove rootfs and kernel images from ignite cache
  block:
    - name: List cached images
      shell:
       cmd: ignite image ls -q 
      register: images
    
    - name: Remove cached images from ignite
      shell:
       cmd: ignite image rm {{ item }}
      loop: "{{ images.stdout_lines }}"
      
    - name: List cached kernels
      shell:
       cmd: ignite kernel ls -q 
      register: kernels
    
    - name: Remove cached kernels from ignite
      shell:
       cmd: ignite kernel rm {{ item }}
      loop: "{{ kernels.stdout_lines }}"
  become: true

- name: Remove the files directory in the bootstrap role
  file:
    path: "./roles/bootstrap/files"
    state: absent

- name: Remove the inventory.ini file
  file:
    path: "./inventory.ini"
    state: absent