# tasks file for dependencies
# this role installs all the packages needed by the nodes to run kubernetes

# It is useful in CI/CD scenarios.
#- name: Wait max {{ time_out }} seconds, for target connection to become reachable/usable
#  wait_for_connection:
#    delay: 10
#    timeout: "{{time_out}}"

- name: Copy drivers_test binary in the machines
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    remote_src: no
    owner: root
    group: root
    mode: '0755'
  with_items: [drivers_test]

- name: Run the drivers_test binary
  block:
    - name: run drivers_test
      command: /root/drivers_test -m
      register: result
      when: inventory_hostname not in execve_bug_kernels

    # Exclude the execve family syscalls when running in bugged kernels
    - name: run drivers_test excluding execve syscall.
      command: /root/drivers_test -m --gtest_filter=-'SyscallEnter.execveE:SyscallEnter.execveatE'
      when: inventory_hostname in execve_bug_kernels
      register: result
  rescue:
     - name: Print when errors
       ansible.builtin.debug:
         msg: "{{ result }}"
