FROM oraclelinux:7

ARG VERSION=3.10.0-1160.92.1.0.2
ARG URL='https://yum.oracle.com/repo/OracleLinux/OL7/MODRHCK/x86_64'

RUN yum install -y \
		binutils-devel \
		clang \
		gcc \
		git \
		iproute \
		kmod \
		libcap-devel \
		llvm \
		make \
		openssh-server \
		rsync \
		systemd \
		tar && \
	curl -L -o kernel.rpm  ${URL}/getPackage/kernel-${VERSION}.el7.x86_64.rpm && \
	curl -L -o devel.rpm   ${URL}/getPackage/kernel-devel-${VERSION}.el7.x86_64.rpm && \
	yum install -y ./*.rpm  && \
	rm -f ./*.rpm  && \
	sed -i -e 's/^AcceptEnv LANG LC_\*$/#AcceptEnv LANG LC_*/' /etc/ssh/sshd_config && \
	echo 'UseDNS no' >> /etc/ssh/sshd_config && \
	echo "root:root" | chpasswd && \
	curl -LO https://cmake.org/files/v3.16/cmake-3.16.7-Linux-x86_64.tar.gz && \
	tar -xaf cmake-3.16.7-Linux-x86_64.tar.gz && \
	rm -f cmake-3.16.7-Linux-x86_64.tar.gz && \
	mv cmake-3.16.7-Linux-x86_64   /opt/cmake-3.16.7 && \
	ln -sf /opt/cmake-3.16.7/bin/* /usr/bin/ && \
	mkdir -p /lib/modules/${VERSION}.el7.x86_64/ && \
	ln -s /usr/src/kernels/${VERSION}.el7.x86_64/ /lib/modules/${VERSION}.el7.x86_64/build
