name: ansible-lint
on:
  pull_request:


jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@9765b8704b2c3f4ab782815b528e0393662e1c04 # v25.7.0
        with:
          working_directory: "${{ github.workspace }}/ansible-playbooks"
          requirements_file: "${{ github.workspace }}/requirements.yml"
