# Playbook used to build modern bpf skeleton.

- name: Build bpf skeleton on designated builder VM
  hosts: "fedora-builder"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Create cmake output dir
      ansible.builtin.file:
        path: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
        state: directory
        mode: "0755"
      register: cmake_result

    - name: Prepare cmake for repository
      ansible.builtin.command:
        cmd: >
             cmake
             -DUSE_BUNDLED_DEPS=ON
             -DBUILD_LIBSCAP_MODERN_BPF=ON
             -DBUILD_LIBSCAP_GVISOR=OFF
             -DCREATE_TEST_TARGETS=OFF
             ..
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
      changed_when: false
      register: cmake_result

    - name: Build skeleton
      ansible.builtin.command:
        cmd: make ProbeSkeleton -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
      changed_when: false
      register: cmake_result

    - name: Fetch the skeleton file
      ansible.builtin.fetch:
        src: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build/skel_dir/bpf_probe.skel.h"
        dest: /tmp/
        flat: true
