# Playbook used to build and distribute drivers_test to all vms.

- name: Build drivers_test on designated builder
  hosts: "centos-builder"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Copy bpf skeleton to centos builder
      ansible.builtin.copy:
        src: "/tmp/bpf_probe.skel.h"
        dest: "/tmp"
        mode: '0755'

    - name: Create cmake output dir
      ansible.builtin.file:
        path: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
        state: directory
        mode: "0755"
      register: cmake_result

    - name: Prepare cmake for repository
      ansible.builtin.shell:
        cmd: |
             source /opt/rh/devtoolset-9/enable &&
             cmake \
             -DCMAKE_BUILD_TYPE=Release \
             -DBUILD_LIBSCAP_MODERN_BPF=ON \
             -DMODERN_BPF_SKEL_DIR=/tmp \
             -DBUILD_DRIVER=Off \
             -DBUILD_BPF=Off \
             -DBUILD_LIBSCAP_GVISOR=OFF \
             -DENABLE_DRIVERS_TESTS=On \
             -DCREATE_TEST_TARGETS=On \
             -DENABLE_IA32_TESTS=Off \
             -DSCAP_FILES_SUITE_ENABLE=Off \
             ..
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      changed_when: false
      register: cmake_result

    - name: Build drivers_test with modern probe
      ansible.builtin.shell:
        cmd: source /opt/rh/devtoolset-9/enable && make drivers_test -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      changed_when: false
      register: cmake_result

    - name: Fetch the drivers_test binary
      ansible.builtin.fetch:
        src: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build/test/drivers/drivers_test"
        dest: "/tmp/"
        flat: true

- name: Play that distributes drivers_test binary to VMs
  hosts: "machines"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Copy drivers_test binary to all VMs
      ansible.builtin.copy:
        src: "/tmp/drivers_test"
        dest: "/tmp"
        mode: '0755'
      become: false
