# Playbook used to run scap-open-test role.
# Check the role for more information

- name: Include build-skeleton playbook
  import_playbook: build-skeleton.yml
- name: Include build-scap-open playbook
  import_playbook: build-scap-open.yml

- name: Play that runs probes tests using scap-open binary
  hosts: "machines"
  gather_facts: true
  remote_user: "{{ user }}"
  become: true
  serial: 30
  roles:
    - scap_open

- name: Remove artifacts from localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove artifacs
      ansible.builtin.file:
        path: "./roles/scap_open/files/"
        state: absent
      with_items:
        - "/tmp/scap-open"
        - "/tmp/bpf_probe.skel.h"
