# Playbook used to run scap-open-test role.
# Check the role for more information

- name: Build bpf skeleton on designated builder VM
  hosts: "fedora-builder"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Create cmake output dir
      ansible.builtin.file:
        path: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
        state: directory
        mode: "0755"
      register: cmake_result

    - name: Prepare cmake for repository
      ansible.builtin.command:
        cmd: >
             cmake
             -DUSE_BUNDLED_DEPS=ON
             -DBUILD_LIBSCAP_MODERN_BPF=ON
             -DBUILD_LIBSCAP_GVISOR=OFF
             -DCREATE_TEST_TARGETS=OFF
             ..
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
      changed_when: false
      register: cmake_result

    - name: Build skeleton
      ansible.builtin.command:
        cmd: make ProbeSkeleton -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build"
      changed_when: false
      register: cmake_result

    - name: Fetch the skeleton file
      ansible.builtin.fetch:
        src: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/skeleton-build/skel_dir/bpf_probe.skel.h"
        dest: /tmp/
        flat: true

- name: Build scap-open on designated builder
  hosts: "centos-builder"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Copy bpf skeleton to centos builder
      ansible.builtin.copy:
        src: "/tmp/bpf_probe.skel.h"
        dest: "/tmp"
        mode: '0755'

    - name: Create cmake output dir
      ansible.builtin.file:
        path: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
        state: directory
        mode: "0755"
      register: cmake_result

    - name: Prepare cmake for repository
      ansible.builtin.shell:
        cmd: |
             source /opt/rh/devtoolset-9/enable &&
             cmake \
             -DCMAKE_BUILD_TYPE=Release \
             -DBUILD_LIBSCAP_MODERN_BPF=ON \
             -DMODERN_BPF_SKEL_DIR=/tmp \
             -DBUILD_DRIVER=Off \
             -DBUILD_BPF=Off \
             -DBUILD_LIBSCAP_GVISOR=OFF \
             -DCREATE_TEST_TARGETS=Off \
             ..
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      changed_when: false
      register: cmake_result

    - name: Build scap-open with modern probe
      ansible.builtin.shell:
        cmd: source /opt/rh/devtoolset-9/enable && make scap-open -j {{ cpus }}
        chdir: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build"
      changed_when: false
      register: cmake_result

    - name: Fetch the scap-open binary
      ansible.builtin.fetch:
        src: "{{ remote_repos_folder }}/repos/{{ repos['libs'].name }}/build/libscap/examples/01-open/scap-open"
        dest: "/tmp/"
        flat: true

- name: Play that distributes scap-open binary to VMs
  hosts: "machines"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Copy scap-open binary to all VMs
      ansible.builtin.copy:
        src: "/tmp/scap-open"
        dest: "/tmp"
        mode: '0755'
      become: false

- name: Play that runs probes tests using scap-open binary
  hosts: "machines"
  gather_facts: true
  remote_user: "{{ user }}"
  become: true
  serial: 30
  roles:
    - scap_open

- name: Remove artifacts from localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove artifacs
      ansible.builtin.file:
        path: "./roles/scap_open/files/"
        state: absent
      with_items:
        - "/tmp/scap-open"
        - "/tmp/bpf_probe.skel.h"
